image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - dist
      - LICENSE.md
      - README.md
      - package.json
    expire_in: 5 minutes
  script:
    - npm install
    - npm run build

deploy-to-npm:
  stage: deploy
  dependencies:
    - build
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
    - npm publish
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]$/
